package mx.edu.ittepic.myapplication

import android.content.Context
import android.database.sqlite.SQLiteDatabase
import android.database.sqlite.SQLiteOpenHelper

class BaseDatos(
    context : Context?,
    name : String?,
    cursor : SQLiteDatabase.CursorFactory?,
    version : Int

):SQLiteOpenHelper(context, name, cursor, version) {
    override fun onCreate(db:SQLiteDatabase?){
        db?.execSQL("CREATE TABLE EMPRESA (IDEMPRESA INTEGER PRIMARY KEY AUTOINCREMENT, DESCRIPCION VARCHAR(30), DOMICILIO VARCHAR (30))")
        db?.execSQL("CREATE TABLE CLIENTE (NOTELEFONO VARCHAR(30) PRIMARY KEY, NOMBRE VARCHAR(400), DOMICILIO VARCHAR(400), IDEMPRESA INTEGER, FOREIGN KEY (IDEMPRESA) REFERENCES EMPRESA(IDEMPRESA))")
        db?.execSQL("CREATE TABLE COMPRA (IDCOMPRA INTEGER PRIMARY KEY AUTOINCREMENT, FECHA DATE, IDCLIENTE VARCHAR(30), TOTAL FLOAT, FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTE(NOTELEFONO))")
        db?.execSQL("CREATE TABLE ALMACEN (IDALMACEN INTEGER PRIMARY KEY AUTOINCREMENT, PRODUCTO VARCHAR(400), CANTIDAD INTEGER, PRECIO FLOAT)")
        db?.execSQL("CREATE TABLE DETALLECOMPRA (IDDETALLE INTEGER PRIMARY KEY AUTOINCREMENT, IDALMACEN INTEGER, CANTIDAD INTEGER, PRECIO FLOAT, IDCOMPRA INTEGER, FOREIGN KEY (IDCOMPRA) REFERENCES COMPRA(IDCOMPRA), FOREIGN KEY (IDALMACEN) REFERENCES ALMACEN(IDALMACEN))")
    }
    override fun onUpgrade(db:SQLiteDatabase?, oldVersion: Int, newVersion: Int){

    }
}